tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "nektos/tap"
tap "semaphoreci/tap"
tap "twpayne/taps"
cask "adoptopenjdk8"
brew "sqlite"
brew "openssl@1.1"
brew "ansible"
brew "coreutils"
brew "asdf"
brew "cmake"
brew "ffmpeg"
brew "dcmtk"
brew "docker", link: false
brew "graphviz"
brew "eralchemy", link: false
brew "fish"
brew "gdcm"
brew "git"
brew "gnupg"
brew "graphviz"
brew "hivemind"
brew "hub"
brew "mas"
brew "mosh"
brew "neo4j"
brew "nmap"
brew "micro"
brew "neo4j", restart_service: true
brew "neovim"
brew "openjdk"
brew "tmux"
brew "overmind"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "sshpass"
brew "redis", restart_service: true
brew "task"
brew "telnet"
brew "tree"
brew "wget"
brew "wxmac"
brew "yadm"
brew "github/gh/gh"
brew "nektos/tap/act"
brew "semaphoreci/tap/sem"
cask "1password"
cask "1password-cli"
cask "adoptopenjdk8-jre"
cask "alfred"
cask "arq"
cask "background-music"
cask "balenaetcher"
cask "bartender"
cask "brave-browser"
cask "dash"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "gephi"
cask "glyphfinder"
cask "google-chrome"
cask "graphiql"
cask "handbrake"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "kite"
cask "logitech-options"
cask "ngrok"
cask "notion"
cask "paw"
cask "postico"
cask "rescuetime"
cask "slack"
cask "spectacle"
cask "spotify"
cask "stoplight-studio"
cask "vagrant"
cask "virtualbox"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zerotier-one"
cask "zoomus"
mas "Amphetamine", id: 937984704
mas "Deliveries", id: 924726344
mas "Diagrams", id: 1276248849
mas "Fantastical", id: 975937182
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
